name: sqlite3_flutter_libs
description: "Stub package — incompatible avec sqlcipher_flutter_libs. Ne pas utiliser."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: none
