import { StyleSheet } from "react-native";
import { colors, fonts, fontSize, fontWeight, radius, shadows, spacing } from "../../theme/tokens";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  headerSafe: { backgroundColor: colors.bgCard },
  body: { flex: 1 },
  bodyContent: {
    paddingHorizontal: spacing.s14,
    paddingTop: spacing.s18,
    paddingBottom: spacing.s24,
  },
  row2: { flexDirection: "row", gap: 12 },
  col: { flex: 1, minWidth: 0 },
  sectionGap: { marginTop: spacing.s20 },
  fieldLabel: {
    fontFamily: fonts.sans,
    fontSize: fontSize.eyebrow,
    fontWeight: fontWeight.semiBold,
    color: colors.textSecond,
    marginBottom: 6,
  },
  textarea: {
    minHeight: 72,
    paddingHorizontal: 11,
    paddingVertical: 14,
    borderRadius: radius.field,
    borderWidth: 1.5,
    borderColor: colors.borderMid,
    backgroundColor: colors.bgCard,
  },
  textareaInput: {
    fontFamily: fonts.sans,
    fontSize: fontSize.bodyLg,
    color: colors.textPrimary,
    padding: 0,
    minHeight: 44,
    textAlignVertical: "top",
  },
  consentCard: {
    backgroundColor: colors.bgCard,
    borderRadius: radius.cardLg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    paddingHorizontal: 15,
    ...shadows.sm,
  },
  consentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 7,
  },
  consentRowBorder: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  pressed: { opacity: 0.85 },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.borderMid,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.bgCard,
  },
  checkboxChecked: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  consentLabel: {
    flex: 1,
    fontFamily: fonts.sans,
    fontSize: 13,
    color: colors.textSecond,
  },
  consentErrorText: {
    marginTop: spacing.s8,
    fontFamily: fonts.sans,
    fontSize: fontSize.caption,
    color: colors.red,
  },
  consentEditHint: {
    marginTop: spacing.s8,
    marginBottom: spacing.s8,
    fontFamily: fonts.sans,
    fontSize: fontSize.caption,
    color: colors.textMuted,
  },
  selectError: {
    fontFamily: fonts.sans,
    fontSize: fontSize.caption,
    color: colors.red,
  },
  draftBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.amberLight,
    borderRadius: radius.field,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s10,
    marginBottom: spacing.s14,
  },
  draftBannerText: {
    fontFamily: fonts.sans,
    fontSize: fontSize.caption,
    fontWeight: fontWeight.semiBold,
    color: colors.amber,
  },
  draftBannerAction: {
    fontFamily: fonts.sans,
    fontSize: fontSize.caption,
    fontWeight: fontWeight.bold,
    color: colors.amber,
    textDecorationLine: "underline",
  },
  actionBar: {
    backgroundColor: colors.bgCard,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    ...shadows.actionBar,
  },
  actionBarInner: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 4,
    gap: 8,
  },
  errorBanner: {
    marginTop: spacing.s14,
    padding: spacing.s12,
    backgroundColor: colors.redLight,
    color: colors.red,
    borderRadius: radius.field,
    fontFamily: fonts.sans,
    fontSize: 13,
  },
});
